# Generated by Django 4.2.4 on 2023-08-03 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tareport',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
