# Generated by Django 4.2.4 on 2023-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('members', models.ManyToManyField(to='ceapp.member')),
            ],
        ),
    ]
