# Generated by Django 4.2.4 on 2023-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0007_questiontext_questionoption_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.CharField(max_length=500)),
                ('rights', models.CharField(max_length=500)),
                ('homepage', models.CharField(max_length=500)),
            ],
        ),
    ]
