# Generated by Django 4.2.4 on 2023-08-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0009_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_number', models.CharField(max_length=10)),
                ('teacher_name', models.CharField(max_length=255)),
                ('class_time', models.CharField(max_length=100)),
                ('ta_class', models.CharField(max_length=100, null=True)),
                ('channel_link', models.CharField(max_length=400)),
                ('ta', models.ManyToManyField(null=True, to='ceapp.ta')),
            ],
        ),
    ]
