# Generated by Django 4.2.4 on 2023-08-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0010_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='channel_link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='ta',
            field=models.ManyToManyField(blank=True, to='ceapp.ta'),
        ),
    ]
