# Generated by Django 4.2.4 on 2023-08-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0011_class_image_alter_class_channel_link_alter_class_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareport',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareport',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
