# Generated by Django 4.2.4 on 2023-09-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0012_tareport_email_tareport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
