# Generated by Django 4.2.4 on 2023-10-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0013_post_date_post_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
    ]
