# Generated by Django 4.2.4 on 2023-10-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0014_remove_post_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='teacher',
        ),
    ]
