# Generated by Django 4.2.4 on 2023-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0015_remove_ta_subject_remove_ta_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ssa',
            name='members',
            field=models.ManyToManyField(blank=True, to='ceapp.member'),
        ),
    ]
