# Generated by Django 4.2.4 on 2023-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0016_alter_class_image_alter_ssa_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
